Calculate criminal tendency
LABSS/PROTON-OC pull request #210
Opened 2020-10-22 06:42 UTC by Kubasinska

2020-10-27 18:39 UTC, mariopaolucci requested changes
Let's integrate those small comments and pass it. I have added a commit that needs to be checked, too, so have a look.

2020-10-27 18:39 UTC, mariopaolucci commented on mesa/Person.py
> +                    self.m.intervention_is_on() and self.m.oc_members_scrutinize) else 1.0
let's get rid of `and not (self.m.intervention_is_on() and self.m.oc_members_scrutinize)`. It is useless.

2020-10-28 08:55 UTC, Kubasinska reviewed
I fixed the docstrings and made the required changes.

2020-10-28 08:55 UTC, Kubasinska commented on mesa/Person.py
> +    def factors_c(self):
I replaced with update_criminal_tendency

2020-10-28 10:20 UTC, mariopaolucci approved these changes

2020-10-28 10:25 UTC, merged