Step#3
LABSS/PROTON-OC pull request #227
Opened 2020-11-06 13:48 UTC by Kubasinska

2020-11-06 13:53 UTC, Kubasinska commented on mesa/Person.py
> -    def family(self): # maybe add self?
Changed with Person.family_link_neighbors(), I created this function and realized afterwards that it already existed!

2020-11-11 09:46 UTC, mariopaolucci requested changes

2020-11-11 09:46 UTC, mariopaolucci commented on mesa/Employer.py
> +        self.my_jobs.append(newjob)
You really didn't like my `Set`s...

2020-11-11 09:46 UTC, mariopaolucci commented on mesa/extra.py
> +        return list(rng_istance.choice(agentset,n, replace=False))
whitespace `,n, repla`

2020-11-11 09:46 UTC, mariopaolucci commented on mesa/mesaPROTON_OC.py
> +        self.removed_fatherships = list()
I don't get the whitepspacing here.. removed_fathership should go under some category (I'd keep it in the interventions area)

2020-11-11 09:46 UTC, mariopaolucci commented on mesa/mesaPROTON_OC.py
> +            support_set = extra.at_most([support_agent for support_agent in self.schedule.agents if support_agent.num_crimes_committed == 0 and support_agent.age() > agent.age() and support_agent !=
double spaces `50,  `

2020-11-11 09:46 UTC, mariopaolucci commented on mesa/mesaPROTON_OC.py
> +            support_set = extra.at_most([support_agent for support_agent in self.schedule.agents if support_agent.num_crimes_committed == 0 and support_agent.age() > agent.age() and support_agent !=
Remove unnecessary `support_agent != agent` (same age)

2020-11-11 09:46 UTC, mariopaolucci commented on mesa/mesaPROTON_OC.py
> +                kid.neighbors.get("parent").remove(kid.father)
Not updating the `father` variable is planned? Add comment in case

2020-11-11 11:23 UTC, Kubasinska commented
Thanks for the comments, changes made, I await confirmation for the merge.

2020-11-12 19:03 UTC, mariopaolucci approved these changes

2020-11-12 22:04 UTC, merged